# Generated by Django 2.2.6 on 2020-01-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '0004_delete_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('students', models.ManyToManyField(to='assignment.Student')),
            ],
        ),
    ]
