# Generated by Django 2.2.6 on 2020-02-11 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200211_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assigments',
        ),
        migrations.AddField(
            model_name='course',
            name='assigments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Assignment'),
        ),
    ]
