# Generated by Django 2.2.6 on 2020-02-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20200211_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assigments',
        ),
        migrations.AddField(
            model_name='course',
            name='assigments',
            field=models.ManyToManyField(blank=True, null=True, to='classes.Assignment'),
        ),
    ]
