# Generated by Django 3.0.2 on 2020-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20200213_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
