# Generated by Django 2.2.6 on 2020-03-03 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='earned_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.Student'),
            preserve_default=False,
        ),
    ]
