# Generated by Django 2.2.6 on 2020-01-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
