# Generated by Django 2.2.6 on 2020-02-14 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0005_auto_20200213_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present'), ('excused', 'Excused'), ('tardy', 'Tardy')], max_length=20)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Student')),
            ],
        ),
    ]
