# Generated by Django 2.2.6 on 2020-02-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20200225_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattendance',
            name='students',
            field=models.ManyToManyField(null=True, through='attendance.Attendance', to='classes.Student'),
        ),
    ]
