# Generated by Django 2.2.6 on 2020-03-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_auto_20200303_2312'),
        ('attendance', '0004_remove_courseattendance_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseattendance',
            name='students',
            field=models.ManyToManyField(null=True, through='attendance.Attendance', to='classes.Student'),
        ),
    ]
