# Generated by Django 2.2.6 on 2020-03-04 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_courseattendance_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseattendance',
            name='students',
        ),
    ]
